### ISSUE TITLE
Wrong python import

### ISSUE THREAD

**Issue by jbuchermn** [rzaluska/deoplete-rtags#1]
Currently the plugin crashes upon startup. This is due to

`from deoplete.sources.base import Base`,

which should be

`from deoplete.source.base import Base`

**Comment by rzaluska** [comment]
Feel free fix it and create a pull request.

I am not maintaining this project anymore but contributions are still welcome. (Probably I should add this information to Readme)

**Comment by jbuchermn** [comment]
I created a PR also containing some minor changes in the RTags API

**Comment by rzaluska** [comment]
Merged into master. You can close this issue.

**Comment by jbuchermn** [comment]
Thank you!
